version: "3.8"

services:
  customer-service:
    build:
      context: ./customer-service
    container_name: customer-service
    ports:
      - "8080:8080"

  order-service:
    build:
      context: ./order-service
    container_name: order-service
    ports:
      - "8081:8081"
    depends_on:
      - customer-service
